
-- Compiled using gm_blueprints v1.6 ( https://github.com/ZakBlystone/gmod_blueprints )
AddCSLuaFile()
local data = {
	keys = {
		editor_graphmodule_editevent = "Edit Event",
		editor_graphmodule_editgraphpins = "Edit Pins",
		editor_graphmodule_editstruct = "Edit Struct",
		editor_graphmodule_eventlist = "Events",
		editor_graphmodule_graphlist = "Graphs",
		editor_graphmodule_structlist = "Structs",
		editor_graphmodule_variablelist = "Variables",
		editor_nodelib_grouplist = "Groups",
		editor_nodelib_nodelist = "Nodes",
		editor_nodelib_structlist = "Structs",
		file_about = "About",
		file_files = "Files",
		file_files_desc = "Files",
		file_help = "Help",
		file_import = "Import",
		file_list_client = "Local Files",
		file_list_server = "Server Files",
		file_newmodule = "New Module",
		file_refresh_local = "Refresh Local Files",
		file_users = "Users",
		file_users_desc = "Users",
		list_rename = "Rename",
		menu_export = "Export",
		menu_export_lua = "Export Lua script",
		menu_export_shareable = "Export shareable key",
		menu_localinstall = "Local: Install",
		menu_localuninstall = "Local: Uninstall",
		menu_save = "Save",
		menu_sendtoserver = "Send to server",
		module_default_desc = "description",
		module_default_name = "unnamed",
		module_effect_desc = "A Clientside Effect you can dispatch using util.Effect",
		module_effect_name = "Effect",
		module_entity_desc = "A Scripted Entity you can spawn in the world",
		module_entity_name = "Entity",
		module_loc_desc = "Localization data for the editor",
		module_loc_name = "Localization",
		module_mod_desc = "A Basic Script",
		module_mod_name = "Mod",
		module_nodelib_desc = "Custom node library",
		module_nodelib_name = "Node Library",
		module_project_desc = "Project",
		module_project_name = "Project",
		module_submenu_developer = "Developer",
		module_submenu_examples = "Examples",
		module_swep_desc = "A Scripted Weapon you can pick up and shoot",
		module_swep_name = "Weapon",
	},
	locale = "en-us",
}
if CLIENT then
	bplocalization.AddLocTable(data)
end