
-- Compiled using gm_blueprints v1.6 ( https://github.com/ZakBlystone/gmod_blueprints )
AddCSLuaFile()
local data = {
	keys = {
		editor_graphmodule_editevent = "Modifier l'evenement",
		editor_graphmodule_editgraphpins = "Modifier le pin",
		editor_graphmodule_editstruct = "Edit Struct",
		editor_graphmodule_eventlist = "Evenement",
		editor_graphmodule_graphlist = "Graphique",
		editor_graphmodule_structlist = "Structs",
		editor_graphmodule_variablelist = "Variables",
		editor_nodelib_grouplist = "Groupes",
		editor_nodelib_nodelist = "Noeuds",
		editor_nodelib_structlist = "Structs",
		file_about = "Info",
		file_files = "Fichier",
		file_files_desc = "Fichier",
		file_help = "Aide",
		file_import = "Importer",
		file_list_client = "Fichier local",
		file_list_server = "Fichier du serveur",
		file_newmodule = "Nouveau module",
		file_refresh_local = "Actualisé les fichier locaux",
		file_users = "Utilisateur",
		file_users_desc = "Utilisateurs",
		list_rename = "Renomer",
		menu_export = "Exporter",
		menu_export_lua = "Exporter un script lua",
		menu_export_shareable = "Exporter une clé partagable",
		menu_localinstall = "Local: Instaler",
		menu_localuninstall = "Local: désinstaler",
		menu_save = "sauvegarder",
		menu_sendtoserver = "envoyé sur le serveur",
		module_default_desc = "description",
		module_default_name = "Sans nom",
		module_effect_desc = "Un effet côté client que vous pouvez envoyer en utilisant util.Effect",
		module_effect_name = "Effect",
		module_entity_desc = "Une entité scriptée que vous pouvez faire apparaître dans le monde",
		module_entity_name = "Entitée",
		module_loc_desc = "Outil de traduction",
		module_loc_name = "Traduction",
		module_mod_desc = "Un script basic",
		module_mod_name = "Mod",
		module_nodelib_desc = "Bibliothèque de nœuds personnalisée",
		module_nodelib_name = "Bibliothèque de nœuds",
		module_project_desc = "Project",
		module_project_name = "Project",
		module_submenu_developer = "Developer",
		module_submenu_examples = "Examples",
		module_swep_desc = "Une arme scriptée que vous pouvez ramasser et tirer",
		module_swep_name = "Arme",
	},
	locale = "fr-fr",
}
if CLIENT then
	bplocalization.AddLocTable(data)
end